[general]
caption_extension = ".txt"
batch_size = 2
enable_bucket = true
bucket_no_upscale = false
resolution = [256, 256]

[[datasets]]
image_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/cache"
num_repeats = 1

[[datasets]]
video_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/videocache"
num_repeats = 1
frame_extraction = "full"
max_frames = 25
