# turbo.toml
# Lower VRAM / Faster Training at the cost of fine detail preservation
[general]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true # Downscales and upscales images, preserving aspect ratio.
bucket_no_upscale = false 
resolution = [540, 540] # Train images at a resolution of 0.29 Megapixels

[[datasets]]
image_directory = "/workspace/musubi-tuner/dataset" # If you change this, the upload feature in the webui won't work
cache_directory = "/workspace/musubi-tuner/dataset/cache"
num_repeats = 1

[[datasets]]
video_directory = "/workspace/musubi-tuner/dataset"
cache_directory = "/workspace/musubi-tuner/dataset/videocache"
frame_extraction = "full" #start from the beginning of the video
max_frames = 81 #only take 5 seconds
resolution = [218,218] # 0.048 MP For Videos. Will be fast with possible quality degredation
